### ISSUE TITLE
As an engineer I want to Review and build off the earlier comparative analysis, with a more intense focus for tools that can be implemented within our available time and that begin to provide most immediate value.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/10x-qualitative-data#13]
## User story 
As an engineer I want to review and build off the earlier comparative analysis so I can get a sense of other tools that might be implemented early and provide more immediate value. 
  
## Acceptance criteria
- [ ]

**Comment by OpenGlobe** [comment]
Amos to write up a short summary on how we got to our current decision.

**Comment by amoose** [comment]
We looked at a few approaches in place, but ultimately have chosen to use GSA's Office of Customer Experience-provided tool: Qualtrics. This is the preferred tool by the OCE. The _Voice of the Customer_ tool has already been phased out across HHS and is somewhat of a burden for the analytics and content teams because of its bespoke nature. The team does not have the development resources to continue to maintain, let alone improve, the VotC tool.
